### ISSUE TITLE
Write a JavaScript code to take color from user and apply that color to a div tag

### ISSUE THREAD

**Issue by Thepetapixl** [Thepetapixl/Web-Tech-Lab#5]
Take colour using text box or use a drop down box

- [x] Create a html file and JavaScript file in a new folder. 
- [x] Two ways (Choose any 1, both are also appreciated):  
     1.  Input text box:
         - [x] Make a div tag, background color as white, a text box for the color and a button
         - [x] Use JS to change the div tag color 
         - [x] Create a pull request 

    2. Drop down box:
        - [ ] Make a div tag, background color as white, a drop down box for the colors and a button
        - [ ] Use JS to change the div tag color 
        - [ ] Create a pull request 

Note: Please do not contribute to this repository is you are NOT a part of [MIT School Of Engineering](https://www.mituniversity.edu.in/academics/faculty/faculty-of-engineering/mit-school-of-engineering/), [MIT ADT University](https://www.mituniversity.edu.in/), [Loni Kalbhor, Pune](https://goo.gl/maps/3LgFxUmT7Qnrk7dU9)

**Comment by itshally** [comment]
Hi @Thepetapixl , I would like to help you with this :)

**Comment by Thepetapixl** [comment]
Issue resolved find there solution [here](https://github.com/Thepetapixl/Web-Tech-Lab/tree/main/AllJavaScript/DivColorChange).
